server:
  port: 8080

spring:
  # Настраиваем подключение к базе данных
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
